version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ubic-food-management-api-v2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mo5zn9ooi3kw"
s3_prefix = "ubic-food-management-api-v2"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
