on:
  push:
    branches:
      - main
name: deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: sam build --use-container
      - run:
          sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --parameter-overrides \
          ChannelId=${{ secrets.CHANNEL_ID }} \
          ChannelSecret=${{ secrets.CHANNEL_SECRET }} \
          S3BucketName=${{ secrets.S3_BUCKET_NAME }} \
          DomainName=${{ secrets.DOMAIN_NAME }} \
          HostedZoneId=${{ secrets.HOSTED_ZONE_ID }} \
          RedirectUri=${{ secrets.REDIRECT_URI }} \
          CertificateArn=${{ secrets.CERTIFICATE_ARN }} \
          DynamoDBArn=${{ secrets.DYNAMO_DB_ARN }}
          S3Arn=${{ secrets.S3_ARN }}