on:
  push:
name: ci
jobs:

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Up dynamodb & localstack
        run: docker-compose up -d dynamodb-local localstack
        working-directory: local_resource
      - name: Copy aws config
        run: cp -r ./.aws ~/
        working-directory: local_resource 
      - name: Create table
        run: sh create_table.sh
        working-directory: local_resource
      - name: Create bucket
        run: sh create_bucket.sh
        working-directory: local_resource
      - name: Add dummy data
        run: sh add_dummy_data.sh
        working-directory: local_resource
      - name: Run test
        run: docker-compose up go-test --exit-code-from go-test
        working-directory: local_resource

  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: build
        run: sam build